### ISSUE TITLE
Add text outline to Target number mod

### ISSUE THREAD

**Issue by gus-uktena** [ClipplerBlood/icrpgme#13]
Hello, I really love the work you did with this system, thanks!

I've noticed that you added an option to put a white background on the target number. I can only imagine because of the target modifier (hard/easy). What about just changing the modifier color to white and adding a text outline effect (line 3011 in icrpgme.css)? 

```
.timer-target-container .target-mod {
  color: white;
  text-shadow: -2px -2px 0 #000, 2px -2px 0 #000, -2px 2px 0 #000, 2px 2px 0 #000;
  position: absolute;
  right: 0;
  top: 12px;
  font-size: 20px;
}
```
![image](https://github.com/ClipplerBlood/icrpgme/assets/83596301/be349da5-c555-407c-af1f-2ef6df087988)

This way would work for any situation and we wouldn't need an ugly white box to use with dark scene maps (I'm a Warp Shell gm so lots of space adventures  ;-) )

**Comment by mordachai** [comment]
solved

**Comment by ClipplerBlood** [comment]
Hey I'll add this in the upcoming version. Thanks a lot!
