### ISSUE TITLE
Sheet tabs aren't being rendered on Foundry V11

### ISSUE THREAD

**Issue by mclemente** [ClipplerBlood/icrpgme#5]
The content of tabs aren't being rendered because V11's tab rendering checks for the tab class.

The solution is to add a `class="tab"` to every tab's div.

Example:
```diff
- <div data-group="primary-tabs" data-tab="primary">
+ <div class="tab" data-group="primary-tabs" data-tab="primary">
```

**Comment by ClipplerBlood** [comment]
Yo thanks for reporting the issue, but most importantly thanks for providing the fix!!
Really appreciated! 😄
