### ISSUE TITLE
Error after update Build 306 - v11

### ISSUE THREAD

**Issue by gus-uktena** [ClipplerBlood/icrpgme#8]
Today I updated my v11 version to Build 306 (Stable) and the combat tracker (combat encounters) stopped to work. ICRPG package version 1.3.2

To reproduce: select a token char on the screen >> right click >> Select Toggle Combat State (shield & swords icon) >> nothing appears on the Combat Encounters panel.

Console throws this error:

![image](https://github.com/ClipplerBlood/icrpgme/assets/83596301/41aa9cad-583a-4fa4-b34d-1302a5540d99)

**Comment by gus-uktena** [comment]
Full uninstall >> re-install of the module didn't solve the issue (worth the shot :) )

**Comment by ClipplerBlood** [comment]
Thanks for letting me know! 
Should be fixed in the 1.3.3 release :)
