### ISSUE TITLE
Full Character Health Not Displaying Correctly on Character Sheet

### ISSUE THREAD

**Issue by jmmcreynolds** [ClipplerBlood/icrpgme#9]
Running the latest version of Foundry VTT (Version 11 Stable Build 307), and I've noticed that when the Actor is at full health, the character sheet shows "0" (zero) health. Messing around with it some more, it seems like the character sheet shows the inverse of the actual health displayed on the Actor token. For example, at full health on the Actor token (i.e. 10), the character sheet shows zero. If you set the Actor token's health to 7, the character sheet shows 3. If you set the Actor token's health to 1, the character sheet shows 9.

**Comment by ClipplerBlood** [comment]
There is a setting to track damage (i.e. the numbers "go up" when a character takes damage) or to track hp (numbers go down)

If I understood your issue correctly it should be fixed by toggling this setting.

**Comment by jmmcreynolds** [comment]
Ah, got it, thanks! Turning that setting off does seem to solve the issue. I had no idea the setting was there though, I'm fairly new to FVTT. Is there a way that this setting could be called out when first starting up so that others aren't confused? I didn't see it mentioned in the system guide either, but could have just missed it.

If anyone else stumbles across this, you can change this by going to "Game Settings" > Configure Settings" and then scrolling down to the "Index Card RPG: Master Edition" section (or just click it on the left) and unchecking the box for "Track Damage".
